// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkzmfqbljnbosjkfatcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhrem1mcWJsam5ib3Nqa2ZhdGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTgwNzgsImV4cCI6MjA2OTI5NDA3OH0.rIK70GMKt2dXBG0Gl3xFewU0lvRJLcxioDlST2CFxDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});